// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-TPonmEABZCz_k_065LuYQlPeSo07q8',
    appId: '1:503284148548:web:7cb27219cddc13b5768f11',
    messagingSenderId: '503284148548',
    projectId: 'bindsync-f71b4',
    authDomain: 'bindsync-f71b4.firebaseapp.com',
    storageBucket: 'bindsync-f71b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCG-g6KMFV8eieIHlM2Qp5bBxEmiLzUmg',
    appId: '1:503284148548:android:e3bb50f95e7474ee768f11',
    messagingSenderId: '503284148548',
    projectId: 'bindsync-f71b4',
    storageBucket: 'bindsync-f71b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvzNfd1beq2eOB4z5_lhFL6ruAYe5gvcQ',
    appId: '1:503284148548:ios:90193d34ba7f384f768f11',
    messagingSenderId: '503284148548',
    projectId: 'bindsync-f71b4',
    storageBucket: 'bindsync-f71b4.firebasestorage.app',
    iosClientId: '503284148548-r1rs4ogo9evml20scbrfh1a4lbfhlinv.apps.googleusercontent.com',
    iosBundleId: 'site.archax.bindsync.bindsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvzNfd1beq2eOB4z5_lhFL6ruAYe5gvcQ',
    appId: '1:503284148548:ios:90193d34ba7f384f768f11',
    messagingSenderId: '503284148548',
    projectId: 'bindsync-f71b4',
    storageBucket: 'bindsync-f71b4.firebasestorage.app',
    iosClientId: '503284148548-r1rs4ogo9evml20scbrfh1a4lbfhlinv.apps.googleusercontent.com',
    iosBundleId: 'site.archax.bindsync.bindsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3-TPonmEABZCz_k_065LuYQlPeSo07q8',
    appId: '1:503284148548:web:b7a1f9211e8fd825768f11',
    messagingSenderId: '503284148548',
    projectId: 'bindsync-f71b4',
    authDomain: 'bindsync-f71b4.firebaseapp.com',
    storageBucket: 'bindsync-f71b4.firebasestorage.app',
  );
}
